import 'package:flutter/widgets.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class ContentData {
  static const List<ResumeData> experiences = [
    ResumeData(
      time: 'Feb - Jul 2023',
      title: 'Unity Developer, Calian Games Sdn Bhd',
      description:
          'Contributed in developing a mobile strategy game, BiO-X. Designed and implemented in-game systems:\n• Inbox System - Tabbed pages of messages from server (announcement, promo rewards), logs of game battle history.\n• VIP Shop - Tiered VIP system with different level providing increasing benefits.\n• Ads Rewards - Gifted resources by watching ads.\n• Tutorial - A sequence of dialog events explaining gameplay mechanics, directing player to press specific UIs.',
    ),
    ResumeData(
      time: 'Mar - Jun 2016',
      title: 'Software Developer (Internship), Materialise Sdn Bhd',
      description:
          'Developed a simple windows desktop drawing application using C++. Contributed in developing a web application for a system handling crash reports generated by the company\'s proprietary software.',
    ),
    ResumeData(
      time: 'Jun - Jul 2012',
      title: 'Electrician (Internship), ARTUR LESER Elektrotechnik GmbH',
      description:
          'Assisted in some cable and wiring maintenance for buildings.',
    ),
  ];

  static const List<ResumeData> educations = [
    ResumeData(
      time: '2014 - 2018',
      title:
          'Bachelor of Computer Science (Hons) with Specialization in Game Development',
      description: 'Multimedia University, Cyberjaya\nCGPA: 3.89',
    ),
    ResumeData(
      time: '2012 - 2014',
      title: 'Bachelor (B.Eng.) in Mechatronics/Precision Technology',
      description:
          'Technische Hochschule Nürnberg, Nuremberg, Germany\nDropout',
    ),
    ResumeData(
      time: '2010 - 2011',
      title: 'Australian Matriculation Programme (AUSMAT)',
      description: 'KBU International College, Petaling Jaya\nATAR: 96.50',
    ),
  ];

  static const List<SkillData> resumeLanguages = [
    SkillData(label: 'Malay', value: 1.0),
    SkillData(label: 'English', value: 0.95),
  ];

  static const List<SkillCategory> resumeStats = [
    SkillCategory(
      name: 'Programming language:',
      skills: [
        SkillData(label: 'C++', value: 0.95),
        SkillData(label: 'C#', value: 1.0),
        SkillData(label: 'Dart', value: 0.9),
        SkillData(label: 'Javascript', value: 0.8),
        SkillData(label: 'Lua', value: 0.75),
        SkillData(label: 'Rust', value: 0.5),
      ],
    ),
    SkillCategory(
      name: 'Discipline:',
      skills: [
        SkillData(label: 'Game development', value: 1.0),
        SkillData(label: 'Mobile development', value: 0.85),
        SkillData(label: 'Web development', value: 0.75),
        SkillData(label: 'Graphics programming', value: 0.6),
      ],
    ),
    SkillCategory(
      name: 'Game engine:',
      skills: [
        SkillData(label: 'Unity', value: 0.95),
        SkillData(label: 'Unreal Engine', value: 0.85),
      ],
    ),
    SkillCategory(
      name: 'Framework:',
      skills: [
        SkillData(label: 'Flutter', value: 0.8),
      ],
    ),
  ];

  static const List<ProjectData> projects = [
    ProjectData(
      name: 'BiO-X',
      description:
          'Published mobile strategy game developed while working in Calian Games Sdn Bhd. Command various troops that have been mutated by Genie-X.',
      image: 'images/project_BiO-X.png',
      links: [
        ProjectLink('Android'),
        ProjectLink('Unity'),
        ProjectLink.icon(FontAwesomeIcons.facebook,
            url: 'https://www.facebook.com/biox.games'),
      ],
    ),
    ProjectData(
      name: 'ObserVR 2',
      description:
          'A mobile shooting strategy VR game. Use your head movement as a controller to shoot laser beams towards asteroids.',
      image: 'images/project_observr.png',
      links: [
        ProjectLink('Android'),
        ProjectLink('VR'),
        ProjectLink('Unity'),
        ProjectLink.icon(FontAwesomeIcons.github,
            url: 'https://github.com/asyzruffz/ObserVR2'),
      ],
    ),
    ProjectData(
      name: 'Tetronihome',
      description:
          'Game made during a game jam. Using standard Tetris gameplay, construct a structure out of tetronimos around your tenant and build them their dream house!',
      image: 'images/project_tetronihome.png',
      links: [
        ProjectLink('Global Game Jam'),
        ProjectLink('2019'),
        ProjectLink("Page",
            url: 'https://globalgamejam.org/2019/games/tetronihome'),
        ProjectLink.icon(FontAwesomeIcons.github,
            url: 'https://github.com/asyzruffz/Global-Game-Jam-2019'),
      ],
    ),
    ProjectData(
      name: 'Stomp',
      description:
          'Game made during a game jam. Evade from the stomping menace while whittling down the monster\'s health with the missiles around.',
      image: 'images/project_stomp.png',
      links: [
        ProjectLink('Ludum Dare 43'),
        ProjectLink('2018'),
        ProjectLink("Page",
            url: 'https://ldjam.com/events/ludum-dare/43/stomp'),
        ProjectLink.icon(FontAwesomeIcons.github,
            url: 'https://github.com/asyzruffz/Ludum-Dare-43'),
      ],
    ),
    ProjectData(
      name: 'Claustro Escalade',
      description:
          'Game made during a game jam. You are trapped in an enclosed space. You need to get out of here or your mind could not take it.',
      image: 'images/project_claustro.png',
      links: [
        ProjectLink('Ludum Dare 42'),
        ProjectLink('2018'),
        ProjectLink("Page",
            url: 'https://ldjam.com/events/ludum-dare/42/claustro-escalade'),
        ProjectLink.icon(FontAwesomeIcons.github,
            url: 'https://github.com/asyzruffz/Ludum-Dare-42'),
      ],
    ),
    ProjectData(
      name: 'Fowlcard',
      description:
          'Game made during a game jam. This game combines the genre for card games and simulation (rearing livestock) games.',
      image: 'images/project_fowlcard.png',
      links: [
        ProjectLink('Ludum Dare 41'),
        ProjectLink('2018'),
        ProjectLink("Page",
            url: 'https://ldjam.com/events/ludum-dare/41/fowlcard'),
        ProjectLink.icon(FontAwesomeIcons.github,
            url: 'https://github.com/asyzruffz/Ludum-Dare-41'),
      ],
    ),
    ProjectData(
      name: 'Where\'s My Channel?!',
      description:
          'Game made during a game jam. Move the antenna around and look for the correct TV transmission to the correct TV shows!',
      image: 'images/project_wherechannel.png',
      links: [
        ProjectLink('Global Game Jam'),
        ProjectLink('2018'),
        ProjectLink("Page",
            url: 'https://globalgamejam.org/2018/games/wheres-my-channel'),
        ProjectLink.icon(FontAwesomeIcons.github,
            url: 'https://github.com/asyzruffz/Global-Game-Jam-2018'),
      ],
    ),
    ProjectData(
      name: 'Find Out Yourself',
      description:
          'Game made during a game jam. We are running out of power! It is up to you to turn on the power back.',
      image: 'images/project_findout.png',
      links: [
        ProjectLink('Ludum Dare 39'),
        ProjectLink('2017'),
        ProjectLink("Page",
            url: 'https://ldjam.com/events/ludum-dare/39/find-out-yourself'),
        ProjectLink.icon(FontAwesomeIcons.github,
            url: 'https://github.com/asyzruffz/Ludum-Dare-39'),
      ],
    ),
    ProjectData(
      name: 'See You Again',
      description:
          'Game made during a game jam. When you interact with the first person, try to find similar person again.',
      image: 'images/project_seeyouagain.png',
      links: [
        ProjectLink('Ludum Dare 38'),
        ProjectLink('2017'),
        ProjectLink("Page",
            url: 'https://ldjam.com/events/ludum-dare/38/see-you-again'),
        ProjectLink.icon(FontAwesomeIcons.github,
            url: 'https://github.com/asyzruffz/Ludum-Dare-38'),
      ],
    ),
    ProjectData(
      name: 'Lost Frequency',
      description:
          'Game made during a game jam. Find the right frequency and keep the ghosts away to stay sane.',
      image: 'images/project_lostfrequency.jpg',
      links: [
        ProjectLink('Global Game Jam'),
        ProjectLink('2017'),
        ProjectLink("Page",
            url: 'https://globalgamejam.org/2017/games/lost-frequency-0'),
        ProjectLink.icon(FontAwesomeIcons.github,
            url: 'https://github.com/asyzruffz/Global-Game-Jam-2017'),
      ],
    ),
    ProjectData(
      name: 'Oath',
      description:
          'Game made during a game jam. The man must fight all the monsters in the space inside his mind in order to find his wife.',
      image: 'images/project_oath.png',
      links: [
        ProjectLink('Ludum Dare 37'),
        ProjectLink('2016'),
        ProjectLink("Page",
            url:
                'https://web.archive.org/web/20210117104058/http://ludumdare.com/compo/ludum-dare-37/?action=preview&uid=55508'),
        ProjectLink.icon(FontAwesomeIcons.github,
            url: 'https://github.com/asyzruffz/Ludum-Dare-37'),
      ],
    ),
    ProjectData(
      name: 'Trapped in Egypt',
      description:
          'Game made during a game jam. Horus and Seth are busy fighting that they didn\'t realise they\'re in an area covered by traps.',
      image: 'images/project_trapped.png',
      links: [
        ProjectLink('Ludum Dare 36'),
        ProjectLink('2016'),
        ProjectLink("Page",
            url:
                'https://web.archive.org/web/20210423162645/http://ludumdare.com/compo/ludum-dare-36/?action=preview&uid=55508'),
        ProjectLink.icon(FontAwesomeIcons.github,
            url: 'https://github.com/asyzruffz/Ludum-Dare-36'),
      ],
    ),
    ProjectData(
      name: 'Hex-a-cute',
      description:
          'Game made during a game jam. 2-player tile placement game. Defeat your opponent by summoning cute elemental monsters and attacking their base.',
      image: 'images/project_hexacute.png',
      links: [
        ProjectLink('Global Game Jam'),
        ProjectLink('2016'),
        ProjectLink("Page",
            url: 'https://globalgamejam.org/2016/games/hex-cute'),
        ProjectLink.icon(FontAwesomeIcons.github,
            url: 'https://github.com/asyzruffz/Global-Game-Jam-2016'),
      ],
    ),
    ProjectData(
      name: 'Light\'s ON',
      description: 'Game made during a game jam. ',
      image: 'images/project_lightson.png',
      links: [
        ProjectLink('SEA Game Jam'),
        ProjectLink('Level Up KL'),
        ProjectLink('2016'),
      ],
    ),
    ProjectData(
      name: 'Ejen Escape',
      description: 'Game made during a game jam.',
      image: 'images/project_ejenescape.png',
      links: [
        ProjectLink('SEA Game Jam'),
        ProjectLink('Level Up KL'),
        ProjectLink('2017'),
      ],
    ),
    ProjectData(
      name: 'Eterium 2139',
      description: 'Game made during a game jam.',
      image: 'images/project_eterium.png',
      links: [
        ProjectLink('SEA Game Jam'),
        ProjectLink('Level Up KL'),
        ProjectLink('2018'),
      ],
    ),
    ProjectData(
      name: 'Bicker Fight',
      description: 'Game made during a game jam.',
      image: 'images/project_bickerfight.png',
      links: [
        ProjectLink('SEA Game Jam'),
        ProjectLink('Level Up KL'),
        ProjectLink('2019'),
      ],
    ),
    ProjectData(
      name: 'Procedural Floating Island',
      description:
          'Final year project for the bachelor degree developing a procedural 3D terrain generator for floating islands.',
      image: 'images/project_procedural.png',
      links: [
        ProjectLink('C#'),
        ProjectLink('Unity'),
        ProjectLink.icon(FontAwesomeIcons.github,
            url: 'https://github.com/asyzruffz/ProceduralFloatingIsland'),
      ],
    ),
  ];

  static const List<BlogData> blogs = [
    BlogData(
      title: 'Hello, world!',
      date: '10/02/2024',
      image: 'images/blog_banner.jpg',
      summary:
          'Welcome to my personal website! This is my first blog post, and I\'m very excited to share it with you.\nI\'ve always wanted to have my own website, where I can showcase my skills, projects, and interests. I think having a personal website is a great way to express yourself, connect with others, and learn new things.\nIt took me a while to complete this website, but I\'m very proud of the result. I learned a lot along the way, happy to experiment with the usage of dart and Flutter. There are still a lot of quirks and issues that I need to handle.\nI hope you enjoy browsing my website, and feel free to leave me a comment or contact me. I\'d love to hear from you!\nThank you for reading, and stay tuned for more updates!',
    )
  ];
}

class ResumeData {
  final String time;
  final String title;
  final String description;

  const ResumeData({
    required this.time,
    required this.title,
    required this.description,
  });
}

class SkillCategory {
  final String name;
  final List<SkillData> skills;

  const SkillCategory({required this.name, required this.skills});
}

class SkillData {
  final String label;
  final double value;

  const SkillData({required this.label, required this.value});
}

class ProjectData {
  final String name;
  final String description;
  final String? image;
  final List<ProjectLink> links;

  const ProjectData({
    required this.name,
    required this.description,
    this.image,
    this.links = const [],
  });
}

class ProjectLink {
  final String? label;
  final IconData? icon;
  final String? url;

  const ProjectLink(this.label, {this.url}) : icon = null;
  const ProjectLink.icon(this.icon, {this.url}) : label = null;
}

class BlogData {
  final String title;
  final String date;
  final String summary;
  final String? image;

  const BlogData({
    required this.title,
    required this.date,
    required this.summary,
    this.image,
  });
}
