class ContentData {
  static const List<ResumeData> experiences = [
    ResumeData(
      time: 'Feb - Jul 2023',
      title: 'Unity Developer, Calian Games Sdn Bhd',
      description:
          'Contributed in developing a mobile strategy game, BiO-X. Designed and implemented in-game systems:\n• Inbox System - Tabbed pages of messages from server (announcement, promo rewards), logs of game battle history.\n• VIP Shop - Tiered VIP system with different level providing increasing benefits.\n• Ads Rewards - Gifted resources by watching ads.\n• Tutorial - A sequence of dialog events explaining gameplay mechanics, directing player to press specific UIs.',
    ),
    ResumeData(
      time: 'Mar - Jun 2016',
      title: 'Software Developer (Internship), Materialise Sdn Bhd',
      description:
          'Developed a simple windows desktop drawing application using C++. Contributed in developing a web application for a system handling crash reports generated by the company\'s proprietary software.',
    ),
    ResumeData(
      time: 'Jun - Jul 2012',
      title: 'Electrician (Internship), ARTUR LESER Elektrotechnik GmbH',
      description:
          'Assisted in some cable and wiring maintenance for buildings.',
    ),
  ];

  static const List<ResumeData> educations = [
    ResumeData(
      time: '2014 - 2018',
      title:
          'Bachelor of Computer Science (Hons) with Specialization in Game Development',
      description: 'Multimedia University, Cyberjaya\nCGPA: 3.89',
    ),
    ResumeData(
      time: '2012 - 2014',
      title: 'Bachelor (B.Eng.) in Mechatronics/Precision Technology',
      description:
          'Technische Hochschule Nürnberg, Nuremberg, Germany\nDropout',
    ),
    ResumeData(
      time: '2010 - 2011',
      title: 'Australian Matriculation Programme (AUSMAT)',
      description: 'KBU International College, Petaling Jaya\nATAR: 96.50',
    ),
  ];

  static const List<SkillData> resumeLanguages = [
    SkillData(label: 'Malay', value: 1.0),
    SkillData(label: 'English', value: 0.95),
  ];

  static const List<SkillCategory> resumeStats = [
    SkillCategory(
      name: 'Programming language:',
      skills: [
        SkillData(label: 'C++', value: 0.95),
        SkillData(label: 'C#', value: 1.0),
        SkillData(label: 'Dart', value: 0.9),
        SkillData(label: 'Javascript', value: 0.8),
        SkillData(label: 'Lua', value: 0.75),
        SkillData(label: 'Rust', value: 0.5),
      ],
    ),
    SkillCategory(
      name: 'Discipline:',
      skills: [
        SkillData(label: 'Game development', value: 1.0),
        SkillData(label: 'Mobile development', value: 0.85),
        SkillData(label: 'Web development', value: 0.75),
        SkillData(label: 'Graphics programming', value: 0.6),
      ],
    ),
    SkillCategory(
      name: 'Game engine:',
      skills: [
        SkillData(label: 'Unity', value: 0.95),
        SkillData(label: 'Unreal Engine', value: 0.85),
      ],
    ),
    SkillCategory(
      name: 'Framework:',
      skills: [
        SkillData(label: 'Flutter', value: 0.8),
      ],
    ),
  ];

  static const List<ProjectData> projects = [
    ProjectData(
      name: 'BiO-X',
      description:
          'Published mobile strategy game developed while working in Calian Games Sdn Bhd.',
      image: 'images/project_BiO-X.png',
    ),
    ProjectData(
      name: 'ObserVR 2',
      description: 'Description ...',
      image: 'images/project_observr.png',
    ),
    ProjectData(
      name: 'Claustro Escalade',
      description: 'Description ...',
      image: 'images/project_claustro.png',
    ),
    ProjectData(
      name: 'Stomp',
      description: 'Description ...',
      image: 'images/project_stomp.png',
    ),
    ProjectData(
      name: 'Fowlcard',
      description: 'Description ...',
      image: 'images/project_fowlcard.png',
    ),
    ProjectData(
      name: 'See You Again',
      description: 'Description ...',
      image: 'images/project_seeyouagain.png',
    ),
    ProjectData(
      name: 'Find Out Yourself',
      description: 'Description ...',
      image: 'images/project_findout.png',
    ),
    ProjectData(
      name: 'Oath',
      description: 'Description ...',
      image: 'images/project_oath.png',
    ),
    ProjectData(
      name: 'Trapped in Egypt',
      description: 'Description ...',
      image: 'images/project_trapped.png',
    ),
    ProjectData(
      name: 'Tetronihome',
      description: 'Description ...',
      image: 'images/project_tetronihome.png',
    ),
    ProjectData(
      name: 'Where\'s My Channel?!',
      description: 'Description ...',
      image: 'images/project_wherechannel.png',
    ),
    ProjectData(
      name: 'Lost Frequency',
      description: 'Description ...',
      image: 'images/project_lostfrequency.jpg',
    ),
    ProjectData(
      name: 'Hex-a-cute',
      description: 'Description ...',
      image: 'images/project_hexacute.png',
    ),
    ProjectData(
      name: 'Bicker Fight',
      description: 'Description ...',
      image: 'images/project_bickerfight.png',
    ),
    ProjectData(
      name: 'Eterium 2139',
      description: 'Description ...',
      image: 'images/project_eterium.png',
    ),
    ProjectData(
      name: 'Ejen Escape',
      description: 'Description ...',
      image: 'images/project_ejenescape.png',
    ),
    ProjectData(
      name: 'Light\'s ON',
      description: 'Description ...',
      image: 'images/project_lightson.png',
    ),
    ProjectData(
      name: 'Procedural Floating Island',
      description:
          'Final year project for the bachelor degree developing a procedural 3D terrain generator for floating islands.',
      image: 'images/project_procedural.png',
    ),
  ];

  static const List<BlogData> blogs = [
    BlogData(
      title: 'Hello, world!',
      date: '10/02/2024',
      summary:
          'Welcome to my personal website! This is my first blog post, and I\'m very excited to share it with you.\nI\'ve always wanted to have my own website, where I can showcase my skills, projects, and interests. I think having a personal website is a great way to express yourself, connect with others, and learn new things.\nIt took me a while to complete this website, but I\'m very proud of the result. I learned a lot along the way, happy to experiment with the usage of dart and Flutter. There are still a lot of quirks and issues that I need to handle.\nI hope you enjoy browsing my website, and feel free to leave me a comment or contact me. I\'d love to hear from you!\nThank you for reading, and stay tuned for more updates!',
    )
  ];
}

class ResumeData {
  final String time;
  final String title;
  final String description;

  const ResumeData({
    required this.time,
    required this.title,
    required this.description,
  });
}

class SkillCategory {
  final String name;
  final List<SkillData> skills;

  const SkillCategory({required this.name, required this.skills});
}

class SkillData {
  final String label;
  final double value;

  const SkillData({required this.label, required this.value});
}

class ProjectData {
  final String name;
  final String description;
  final String? image;
  final String? link;

  const ProjectData({
    required this.name,
    required this.description,
    this.image,
    this.link,
  });
}

class BlogData {
  final String title;
  final String date;
  final String summary;
  final String? image;

  const BlogData({
    required this.title,
    required this.date,
    required this.summary,
    this.image,
  });
}
