class Tag {
  static const String nickname = 'Asyraf';
  static const String fullname = 'Muhammad Asyraf bin Ibrahim';
  static const String dateOfBirth = '09/10/1992';
  static const String email = 'm.asyraf.ibr@gmail.com';
  static const String phoneNumber = '+6013 464 2899';
  static const String address =
      'No. 59, Lorong Bukit 4, Taman Bukit,\n  09100 Baling, Kedah, Malaysia';
  static const String address2 =
      'No. 59, Lorong Bukit 4\nTaman Bukit\n09100 Baling, Kedah';

  static const String backgroundImage = 'images/background.png';
  static const String blogImage = 'images/blog_banner.jpg';
  static const String cvFile = 'public/CV by Asyraf.pdf';

  static const String navHome = 'Home';
  static const String navAbout = 'About';
  static const String navResume = 'Resume';
  static const String navPortfolio = 'Portfolio';
  static const String navBlog = 'Blog';
  static const String navContact = 'Contact';

  static const String labelFullname = 'Full Name';
  static const String labelName = 'Name';
  static const String labelBirthdate = 'Birthdate';
  static const String labelEmail = 'Email';
  static const String labelPhone = 'Phone';
  static const String labelAddress = 'Address';
  static const String labelMessage = 'Message';
  static const String labelExperiences = 'Experiences';
  static const String labelEducation = 'Education';
  static const String labelSkills = 'Skills';
  static const String labelLanguages = 'Languages';
  static const String labelReadMore = 'Read more';

  static const String githubLink = 'https://github.com/asyzruffz/';
  static const String linkedinLink =
      'https://www.linkedin.com/in/muhammad-asyraf-bin-ibrahim/';
  static const String mastodonLink = 'https://mastodon.gamedev.place/@ruffz';
  static const String emailLink = 'mailto:m.asyraf.ibr@gmail.com';

  static const String heroGreeting = 'Hello, I am';
  static const String heroJobPosition =
      'Software Developer | Game Developer | Programmer';
  static const String heroDownloadCV = 'Download Resume';

  static const String aboutWhoami = 'Who am I ?';
  static const String aboutRole =
      'A Programmer operating as Software / Game Developer';
  static const String aboutIntroduction =
      'Experienced in game development, I\'m passionate in programming software and games. I\'m an open-minded person, flexible and able to receive constructive criticism. A person adaptable to new environment and able to learn new things quickly.';
  static const String aboutDownloadCV = 'Download My CV';
  static const String aboutPersonalInfo = 'Personal Info';
  static const String aboutMyExpertise = 'My Expertise';
  static const String aboutExpertise1 = 'Programming';
  static const String aboutExpertiseDesc1 =
      'Creating, optimizing, and maintaining codes using a few programming languages.';
  static const String aboutExpertise2 = 'System Design';
  static const String aboutExpertiseDesc2 =
      'Planning and organizing the overall structure, architecture, and components of a game system, defining the goals, scope, specifications, and requirements of the system.';
  static const String aboutExpertise3 = 'Debugging';
  static const String aboutExpertiseDesc3 =
      'Finding and fixing the errors, defects, and glitches that affect the functionality, performance, and quality of a software.';

  static const String resumeExpTime1 = 'Feb - Jul 2023';
  static const String resumeExpRole1 = 'Unity Developer, Calian Games Sdn Bhd';
  static const String resumeExpDesc1 =
      'Contributed in developing a mobile strategy game, BiO-X. Designed and implemented in-game systems:\n• Inbox System - Tabbed pages of messages from server (announcement, promo rewards), logs of game battle history.\n• VIP Shop - Tiered VIP system with different level providing increasing benefits.\n• Ads Rewards - Gifted resources by watching ads.\n• Tutorial - A sequence of dialog events explaining gameplay mechanics, directing player to press specific UIs.';

  static const String resumeExpTime2 = 'Mar - Jun 2016';
  static const String resumeExpRole2 =
      'Software Developer (Internship), Materialise Sdn Bhd';
  static const String resumeExpDesc2 =
      'Developed a simple windows desktop drawing application using C++. Contributed in developing a web application for a system handling crash reports generated by the company\'s proprietary software.';

  static const String resumeExpTime3 = 'Jun - Jul 2012';
  static const String resumeExpRole3 =
      'Electrician (Internship), ARTUR LESER Elektrotechnik GmbH';
  static const String resumeExpDesc3 =
      'Assisted in some cable and wiring maintenance for buildings.';

  static const String resumeEduTime1 = '2014 - 2018';
  static const String resumeEduLevel1 =
      'Bachelor of Computer Science (Hons) with Specialization in Game Development';
  static const String resumeEduDesc1 =
      'Multimedia University, Cyberjaya\nCGPA: 3.89';

  static const String resumeEduTime2 = '2012 - 2014';
  static const String resumeEduLevel2 =
      'Bachelor (B.Eng.) in Mechatronics/Precision Technology';
  static const String resumeEduDesc2 =
      'Technische Hochschule Nürnberg, Nuremberg, Germany\nDropout';

  static const String resumeEduTime3 = '2010 - 2011';
  static const String resumeEduLevel3 =
      'Australian Matriculation Programme (AUSMAT)';
  static const String resumeEduDesc3 =
      'KBU International College, Petaling Jaya\nATAR: 96.50';

  static const List<SkillCategory> resumeStats = [
    SkillCategory(
      category: 'Programming language:',
      skills: [
        SkillData(label: 'C++', value: 0.95),
        SkillData(label: 'C#', value: 1.0),
        SkillData(label: 'Dart', value: 0.9),
        SkillData(label: 'Javascript', value: 0.8),
        SkillData(label: 'Lua', value: 0.75),
        SkillData(label: 'Rust', value: 0.5),
      ],
    ),
    SkillCategory(
      category: 'Discipline:',
      skills: [
        SkillData(label: 'Game development', value: 1.0),
        SkillData(label: 'Mobile development', value: 0.85),
        SkillData(label: 'Web development', value: 0.75),
        SkillData(label: 'Graphics programming', value: 0.6),
      ],
    ),
    SkillCategory(
      category: 'Game engine:',
      skills: [
        SkillData(label: 'Unity', value: 0.95),
        SkillData(label: 'Unreal Engine', value: 0.85),
      ],
    ),
    SkillCategory(
      category: 'Framework:',
      skills: [
        SkillData(label: 'Flutter', value: 0.8),
      ],
    ),
  ];

  static const String resumeLanguage1 = 'Malay';
  static const double resumeLangScore1 = 1.0;
  static const String resumeLanguage2 = 'English';
  static const double resumeLangScore2 = 0.95;

  static const String blogTitle1 = 'Hello, world!';
  static const String blogDate1 = '10/02/2024';
  static const String blogSummary1 =
      'Welcome to my personal website! This is my first blog post, and I\'m very excited to share it with you.\nI\'ve always wanted to have my own website, where I can showcase my skills, projects, and interests. I think having a personal website is a great way to express yourself, connect with others, and learn new things.\nIt took me a while to complete this website, but I\'m very proud of the result. I learned a lot along the way, happy to experiment with the usage of dart and Flutter. There are still a lot of quirks and issues that I need to handle.\nI hope you enjoy browsing my website, and feel free to leave me a comment or contact me. I\'d love to hear from you!\nThank you for reading, and stay tuned for more updates!';

  static const String contactFormTitle = 'Send a message';
  static const String contactInfoTitle = 'Get in touch';
  static const String contactSendBtn = 'Send Message';

  static const String footer = '© 2024 Created with Flutter by Asyraf';
}

class SkillCategory {
  final String category;
  final List<SkillData> skills;

  const SkillCategory({required this.category, required this.skills});
}

class SkillData {
  final String label;
  final double value;

  const SkillData({required this.label, required this.value});
}
