class Tag {
  static const String nickname = 'Asyraf';
  static const String fullname = 'Muhammad Asyraf bin Ibrahim';
  static const String dateOfBirth = '09/10/1992';
  static const String email = 'm.asyraf.ibr@gmail.com';
  static const String phoneNumber = '+6013 464 2899';
  static const String address =
      'No. 59, Lorong Bukit 4, Taman Bukit,\n  09100 Baling, Kedah, Malaysia';
  static const String address2 =
      'No. 59, Lorong Bukit 4\nTaman Bukit\n09100 Baling, Kedah';

  static const String backgroundImage = 'images/background.png';
  static const String cvFile = 'public/CV by Asyraf.pdf';

  static const String navHome = 'Home';
  static const String navAbout = 'About';
  static const String navResume = 'Resume';
  static const String navPortfolio = 'Portfolio';
  static const String navBlog = 'Blog';
  static const String navContact = 'Contact';

  static const String labelFullname = 'Full Name';
  static const String labelName = 'Name';
  static const String labelBirthdate = 'Birthdate';
  static const String labelEmail = 'Email';
  static const String labelPhone = 'Phone';
  static const String labelAddress = 'Address';
  static const String labelMessage = 'Message';
  static const String labelExperiences = 'Experiences';
  static const String labelEducation = 'Education';
  static const String labelSkills = 'Skills';
  static const String labelLanguages = 'Languages';

  static const String githubLink = 'https://github.com/asyzruffz/';
  static const String linkedinLink =
      'https://www.linkedin.com/in/muhammad-asyraf-bin-ibrahim/';
  static const String emailLink = 'mailto:m.asyraf.ibr@gmail.com';

  static const String heroGreeting = 'Hello, I am';
  static const String heroJobPosition =
      'Software Developer | Game Developer | Programmer';
  static const String heroDownloadCV = 'Download Resume';

  static const String aboutWhoami = 'Who am I ?';
  static const String aboutRole =
      'A Programmer operating as Software / Game Developer';
  static const String aboutIntroduction =
      'Experienced in game development, I\'m passionate in programming software and games. I\'m an open-minded person, flexible and able to receive constructive criticism. A person adaptable to new environment and able to learn new things quickly.';
  static const String aboutDownloadCV = 'Download My CV';
  static const String aboutPersonalInfo = 'Personal Info';
  static const String aboutMyExpertise = 'My Expertise';
  static const String aboutExpertise1 = 'Programming';
  static const String aboutExpertiseDesc1 =
      'Creating, optimizing, and maintaining codes using a few programming languages.';
  static const String aboutExpertise2 = 'System Design';
  static const String aboutExpertiseDesc2 =
      'Planning and organizing the overall structure, architecture, and components of a game system, defining the goals, scope, specifications, and requirements of the system.';
  static const String aboutExpertise3 = 'Debugging';
  static const String aboutExpertiseDesc3 =
      'Finding and fixing the errors, defects, and glitches that affect the functionality, performance, and quality of a software.';

  static const String resumeExpTime1 = 'Feb - Jul 2023';
  static const String resumeExpRole1 = 'Unity Developer, Calian Games Sdn Bhd';
  static const String resumeExpDesc1 =
      'Contributed in developing a mobile strategy game, BiO-X. Designed and implemented in-game systems:\n• Inbox System - Tabbed pages of messages from server (announcement, promo rewards), logs of game battle history.\n• VIP Shop - Tiered VIP system with different level providing increasing benefits.\n• Ads Rewards - Gifted resources by watching ads.\n• Tutorial - A sequence of dialog events explaining gameplay mechanics, directing player to press specific UIs.';

  static const String resumeExpTime2 = 'Mar - Jun 2016';
  static const String resumeExpRole2 =
      'Software Developer (Internship), Materialise Sdn Bhd';
  static const String resumeExpDesc2 =
      'Developed a simple windows desktop drawing application using C++. Contributed in developing a web application for a system handling crash reports generated by the company\'s proprietary software.';

  static const String resumeExpTime3 = 'Jun - Jul 2012';
  static const String resumeExpRole3 =
      'Electrician (Internship), ARTUR LESER Elektrotechnik GmbH';
  static const String resumeExpDesc3 =
      'Assisted in some cable and wiring maintenance for buildings.';

  static const String resumeEduTime1 = '2014 - 2018';
  static const String resumeEduLevel1 =
      'Bachelor of Computer Science (Hons) with Specialization in Game Development';
  static const String resumeEduDesc1 =
      'CGPA: 3.89\nMultimedia University, Cyberjaya';

  static const String resumeEduTime2 = '2012 - 2014';
  static const String resumeEduLevel2 =
      'Bachelor (B.Eng.) in Mechatronics/Precision Technology';
  static const String resumeEduDesc2 =
      'Dropout\nTechnische Hochschule Nürnberg, Nuremberg, Germany';

  static const String resumeEduTime3 = '2010 - 2011';
  static const String resumeEduLevel3 =
      'Australian Matriculation Programme (AUSMAT)';
  static const String resumeEduDesc3 =
      'ATAR: 96.50\nKBU International College, Petaling Jaya';

  static const String resumeSkillCat1 = 'Object-oriented:';
  static const String resumeSkill1 = 'C++';
  static const double resumeSkillScore1 = 0.95;
  static const String resumeSkill2 = 'C#';
  static const double resumeSkillScore2 = 1.0;
  static const String resumeSkill3 = 'Java';
  static const double resumeSkillScore3 = 0.8;
  static const String resumeSkillCat2 = 'Game engine:';
  static const String resumeSkill4 = 'Unity';
  static const double resumeSkillScore4 = 0.95;
  static const String resumeSkill5 = 'Unreal Engine';
  static const double resumeSkillScore5 = 0.85;
  static const String resumeSkillCat3 = 'Scripting:';
  static const String resumeSkill6 = 'Javascript';
  static const double resumeSkillScore6 = 0.8;
  static const String resumeSkill7 = 'Lua';
  static const double resumeSkillScore7 = 0.75;
  static const String resumeSkillCat4 = 'Misc:';
  static const String resumeSkill8 = 'Graphics programming';
  static const double resumeSkillScore8 = 0.6;
  static const String resumeSkill9 = 'Web development';
  static const double resumeSkillScore9 = 0.75;

  static const String resumeLanguage1 = 'Malay';
  static const double resumeLangScore1 = 1.0;
  static const String resumeLanguage2 = 'English';
  static const double resumeLangScore2 = 0.95;

  static const String contactFormTitle = 'Send a message';
  static const String contactInfoTitle = 'Get in touch';
  static const String contactSendBtn = 'Send Message';

  static const String footer = '© 2024 Created with Flutter by Asyraf';
}
